### ISSUE TITLE
Cut maps: output files in netcdf format

### ISSUE THREAD

**Issue by StefaniaGrimaldi** [ec-jrc/lisflood-utilities#18]
I have been using cutmaps to retrieve the mask map of the area contributing to an outlet point. 
I think that this function is really useful!

I only noticed some imprecision in the reference system of the netcdf files (e.g. the files my_mask.nc and outlets.nc in the folder tests). Would it be possible to fix this issue?

Here is the message that I see when I run the python code:
 _Writing /xxxxxxx/tests/data/cutmaps/my_mask.nc
Traceback (most recent call last):
  File "test_cutmap.py", line 10, in <module>
    mask,outlets_nc = mask_from_ldd(ldd_pcr, stations)
  File "/home/grimast/anaconda3/envs/lisfloodv3/lib/python3.7/site-packages/lisfloodutilities/cutmaps/cutlib.py", line 243, in mask_from_ldd
    convert(smallmask_map, maskmap_nc, pcr2nc_metadata)
  File "/home/grimast/anaconda3/envs/lisfloodv3/lib/python3.7/site-packages/lisfloodutilities/pcr2nc/__init__.py", line 36, in convert
    writer.finalize()
  File "/home/grimast/anaconda3/envs/lisfloodv3/lib/python3.7/site-packages/lisfloodutilities/writers/nc.py", line 228, in finalize
    self.variable[:, :] = np.array(self.values, dtype=dtype)
  File "netCDF4/_netCDF4.pyx", line 4853, in netCDF4._netCDF4.Variable.__setitem__
  File "/home/grimast/anaconda3/envs/lisfloodv3/lib/python3.7/site-packages/netCDF4/utils.py", line 365, in _StartCountStride
    datashape = broadcasted_shape(shape, datashape)
  File "/home/grimast/anaconda3/envs/lisfloodv3/lib/python3.7/site-packages/netCDF4/utils.py", line 973, in broadcasted_shape
    return np.broadcast(a, b).shape
ValueError: shape mismatch: objects cannot be broadcast to a single shape_

**Comment by domeniconappo** [comment]
Other info
Estensione
0.0000000000000000,-950.0000000000000000 : 1000.0000000000000000,0.0000000000000000

Should be

Estensione | 2500000.0000000000000000,750000.0000000000000000 : 7500000.0000000000000000,5500000.0000000000000000

pixel size: 5000, 5000

![image](https://user-images.githubusercontent.com/7078978/105387420-d0146c00-5c15-11eb-9160-e63ff6423d84.png)

![image](https://user-images.githubusercontent.com/7078978/105387458-dc002e00-5c15-11eb-989a-be20f3957a95.png)

**Comment by domeniconappo** [comment]
```
File "/home/grimast/anaconda3/envs/lisfloodv3/lib/python3.7/site-packages/lisfloodutilities/cutmaps/cutlib.py", line 243, in mask_from_ldd
convert(smallmask_map, maskmap_nc, pcr2nc_metadata)
File "/home/grimast/anaconda3/envs/lisfloodv3/lib/python3.7/site-packages/lisfloodutilities/pcr2nc/init.py", line 36, in convert
writer.finalize()
File "/home/grimast/anaconda3/envs/lisfloodv3/lib/python3.7/site-packages/lisfloodutilities/writers/nc.py", line 228, in finalize
self.variable[:, :] = np.array(self.values, dtype=dtype)
File "netCDF4/_netCDF4.pyx", line 4853, in netCDF4._netCDF4.Variable.setitem
File "/home/grimast/anaconda3/envs/lisfloodv3/lib/python3.7/site-packages/netCDF4/utils.py", line 365, in StartCountStride
datashape = broadcasted_shape(shape, datashape)
File "/home/grimast/anaconda3/envs/lisfloodv3/lib/python3.7/site-packages/netCDF4/utils.py", line 973, in broadcasted_shape
return np.broadcast(a, b).shape
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

Can reproduce this error when stations.txt contains a single item. This is another bug and it's not related to wrong reference systems in netcdf files. Will be fixed on same branch though.
