### ISSUE TITLE
LISFLOOD Utilities Setup Error

### ISSUE THREAD

**Issue by koray-yilmaz** [ec-jrc/lisflood-utilities#39]
Hi,
I followed the installation instructions to setup lisflood utilities. I use conda environment on Windows 11. I got the following errors when I tried installing the utilities. Any help is appreciated.

(lisfloodutils) PS C:\Users\user> pip install lisflood-utilities
Collecting lisflood-utilities
  Using cached lisflood-utilities-0.12.21.tar.gz (50 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-3g8zz3_g\lisflood-utilities_9e00e28daefd43cdb00d344e373f3abd\setup.py", line 44, in <module>
          long_description = f.read()
        File "C:\Users\user\anaconda3\envs\lisfloodutils\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 20893: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by doc78** [comment]
Dear @koray-yilmaz 
I'm sorry but we do not provide support for Windows operating systems.
We suggest to use Linux distribution Ubuntu or CentOS.
King Regards
Carlo
